### PR TITLE
Rebuild UI and i18n support.

### PR DESCRIPTION
**Pull request by logue**

### CODE REVIEW

**Comment by PolCPP** [comment]
Thanks!

On a quick check it looks good to me but let me test it out before merging. @Aida-Enna / @alama , any thoughts?

**Comment by alama** [comment]
Sigh, test and made some changes in alama@b405923db8b52ed04fa07ba057c7e453f4979ce6 (https://github.com/alama/PSO2-Mod-Manager/tree/logue)

I do not know WHY there are cmd command in PostBuild but then again, I use "P:\Pso2MM.Debug\" as my working folder for Debugging/Testing

**Comment by logue** [comment]
Those commands are used to create the mods directory and the thumbnail directory.
Perhaps, if the directory does not exist on the program side, it may be better to implement the program by creating it.

**Comment by PolCPP** [comment]
Ok tried it, and reviewed it more deeply, love the UI, there's a slight issue, i'll try fixing it over the weekend but you may know what's going on.

When i download any mod, it's showing me the "Currently downloading other mods" Error, once i accept it shows the downloading of that mod progress. Seems to happen all times. (And i'm only downloading one mod).

**Comment by PolCPP** [comment]
Ok, found the issue will fix it later. Merging

**Pull request merged**
